# Generated by Django 5.0.7 on 2024-08-13 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_options_alter_customer_table_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_total', models.FloatField()),
                ('offer_amount', models.FloatField()),
                ('totel_amount', models.FloatField()),
                ('delivery_charge', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'verbose_name': 'cartbill',
                'verbose_name_plural': 'cartbills',
                'db_table': 'customer_cartbill',
                'ordering': ['-id'],
            },
        ),
    ]
