# Generated by Django 5.0.7 on 2024-08-14 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addres', models.CharField(max_length=255)),
                ('appartment', models.CharField(max_length=255)),
                ('landmark', models.CharField(max_length=255)),
                ('addres_type', models.CharField(choices=[('work', 'work'), ('home', 'home'), ('other', 'other')], max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'verbose_name': 'addres',
                'verbose_name_plural': 'addres',
                'db_table': 'customer_addres',
                'ordering': ['-id'],
            },
        ),
    ]
