# Generated by Django 5.0.7 on 2024-08-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_addres'),
    ]

    operations = [
        migrations.AddField(
            model_name='addres',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addres',
            name='addres_type',
            field=models.CharField(choices=[('home', 'home'), ('other', 'other'), ('work', 'work')], max_length=255),
        ),
    ]
