# Generated by Django 5.0.7 on 2024-08-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_addres_phone_alter_addres_addres_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addres',
            new_name='Address',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-id'], 'verbose_name': 'address', 'verbose_name_plural': 'addreses'},
        ),
        migrations.RenameField(
            model_name='address',
            old_name='addres',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='addres_type',
            new_name='address_type',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AlterModelTable(
            name='address',
            table='customer_address',
        ),
    ]
