# Generated by Django 5.0.7 on 2024-08-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_rename_addres_address_alter_address_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('home', 'home'), ('work', 'work'), ('other', 'other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
