# Generated by Django 5.0.7 on 2024-08-20 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_cartbill_address_alter_address_address_type'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('other', 'other'), ('work', 'work'), ('home', 'home')], max_length=255),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_total', models.FloatField()),
                ('offer_amount', models.FloatField()),
                ('totel_amount', models.FloatField()),
                ('delivery_charge', models.FloatField()),
                ('appartment', models.CharField(max_length=255)),
                ('landmark', models.CharField(max_length=255)),
                ('phone_number', models.BigIntegerField()),
                ('address_type', models.CharField(choices=[('other', 'other'), ('work', 'work'), ('home', 'home')], max_length=255)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'db_table': 'customer_order',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.food')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.store')),
            ],
            options={
                'verbose_name': 'orderbill',
                'verbose_name_plural': 'orderbills',
                'db_table': 'customer_orderbill',
                'ordering': ['-id'],
            },
        ),
    ]
