# Generated by Django 5.0.7 on 2024-08-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_address_address_type_order_orderbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('home', 'home'), ('other', 'other'), ('work', 'work')], max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_type',
            field=models.CharField(choices=[('home', 'home'), ('other', 'other'), ('work', 'work')], max_length=255),
        ),
    ]
