# Generated by Django 5.0.7 on 2024-08-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_order_order_id_alter_address_address_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('home', 'home'), ('work', 'work'), ('other', 'other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_type',
            field=models.CharField(choices=[('home', 'home'), ('work', 'work'), ('other', 'other')], max_length=255),
        ),
    ]
