# Generated by Django 5.0.7 on 2024-08-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_remove_order_phone_number_alter_address_address_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cartbill',
            field=models.ManyToManyField(to='customer.orderbill'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('work', 'work'), ('other', 'other'), ('home', 'home')], max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_type',
            field=models.CharField(choices=[('work', 'work'), ('other', 'other'), ('home', 'home')], max_length=255),
        ),
    ]
